[package]
name = "wowgen"
version = "0.1.0"
authors = ["Rhea Myers <rhea@myers.studio>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"bitcoin"="0.21"
"bitcoin-wallet"="1.1.0"
"rand"="0.7"